--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/Carbon
build-by-default: true
branches:
- master
projects:
  Carbon:
    path: ""
    model: virion
    type: library
...
